import { Flower } from './flowers/flower';

export const FLOWERS: Flower[] = [
    { flowerId : 1,
    flowerName : 'ANEMONE',
    costOfFlowers : 50,
    discount : 0.1, 
    image: '/assets/images/ANEMONE.jpg'},
    { flowerId : 2,
    flowerName : 'ASTER',
    costOfFlowers : 40,
    discount : 0.1,
image: '/assets/images/ASTER.jpg'},
    { flowerId : 3,
    flowerName : 'BELLFLOWER',
    costOfFlowers : 70,
    discount : 0.1,
    image: '/assets/images/BELLFLOWER.jpg'},
    { flowerId : 4,
    flowerName : 'BLACKEYED SUSAN',
    costOfFlowers : 70,
    discount : 0.1,
    image: '/assets/images/BLACKEYED SUSAN.jpg'},
    { flowerId : 5,
    flowerName : 'CHIVES',
    costOfFlowers : 70,
    discount : 0.1,
    image: '/assets/images/CHIVES.jpg'},
    { flowerId : 6,
    flowerName : 'COREOPSIS',
    costOfFlowers : 70,
    discount : 0.1,
    image: '/assets/images/COREOPSIS.jpg'},
    { flowerId : 7,
    flowerName : 'DAISY',
    costOfFlowers : 70,
    discount : 0.1,
    image: '/assets/images/DAISY.jpg'},
    { flowerId : 8,
    flowerName : 'GAILLARDIA',
    costOfFlowers : 70,
    discount : 0.1,
    image: '/assets/images/GAILLARDIA.jpg'},
    { flowerId : 9,
    flowerName : 'GAZANIA',
    costOfFlowers : 70,
    discount : 0.1,
    image: '/assets/images/GAZANIA.jpg'},
    { flowerId : 10,
    flowerName : 'HIBISCUS',
    costOfFlowers : 70,
    discount : 0.1,
    image: '/assets/images/HIBISCUS.jpg'},
    { flowerId : 11,
    flowerName : 'IRIS',
    costOfFlowers : 70,
    discount : 0.1,
    image: '/assets/images/IRIS.jpg'},
    { flowerId : 12,
    flowerName : 'MARIGOLD',
    costOfFlowers : 70,
    discount : 0.1,
    image: '/assets/images/MARIGOLD.jpg'},
    { flowerId : 13,
    flowerName : 'MOONFLOWER',
    costOfFlowers : 70,
    discount : 0.1,
    image: '/assets/images/MOONFLOWER.jpg'},
    { flowerId : 14,
    flowerName : 'RED VALERIAN',
    costOfFlowers : 70,
    discount : 0.1,
    image: '/assets/images/RED VALERIAN.jpg'},
    { flowerId : 15,
    flowerName : 'ROSE',
    costOfFlowers : 70,
    discount : 0.1,
    image: '/assets/images/ROSE.jpg'},
    { flowerId : 16,
    flowerName : 'SANVITALIA',
    costOfFlowers : 70,
    discount : 0.1,
    image: '/assets/images/SANVITALIA.jpg'},
    { flowerId : 17,
    flowerName : 'SEA LAVENDER',
    costOfFlowers : 70,
    discount : 0.1,
    image: '/assets/images/SEA LAVENDER.jpg'},
    { flowerId : 18,
    flowerName : 'STREPOCARPUS',
    costOfFlowers : 70,
    discount : 0.1,
    image: '/assets/images/STREPOCARPUS.jpg'},
     { flowerId : 19,
    flowerName : 'SUNFLOWER',
    costOfFlowers : 70,
    discount : 0.1,
    image: '/assets/images/SUNFLOWER.jpg'}
];